### PR TITLE
Fix e1000 driver package receive bug

### PR DESCRIPTION
**Pull request by zhangpf**

### CODE REVIEW

**Comment by jiegec** [comment]
How to reproduce?

**Comment by zhangpf** [comment]
Please reference this gist (https://gist.github.com/zhangpf/97b5e03e3910d5fa2bb7986c3ccf03c0) to reproduce the problem.
This fix can resolve this bug.

**Review by jiegec — APPROVED** [review]
LGTM

**Comment by jiegec** [comment]
The document says:

```
If software statically allocates buffers, and uses memory read to check for completed descriptors, it simply has to zero the status byte in the descriptor to make it ready for reuse by hardware. This is not a hardware requirement (moving the hardware tail pointer is), but is necessary for performing an in–memory scan.
```

Can you test to clear the status byte instead of one bit?

**Comment by jiegec** [comment]
It seems that before moving to isomorphic_drivers, it is written like:

```
-            let buffer = unsafe {
-                slice::from_raw_parts(
-                    driver.recv_buffers[index] as *const u8,
-                    recv_desc.len as usize,
-                )
-            };
-
-            recv_desc.status = recv_desc.status & !1;
-
-            rdt = (rdt + 1) % recv_queue_size as u32;
-            e1000[E1000_RDT].write(rdt);
-
-            Some((E1000RxToken(buffer.to_vec()), E1000TxToken(self.clone())))

```

**Pull request merged**
